import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shard/Navbar";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/shard/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white text-zinc-900 dark:bg-[#040712] dark:text-zinc-100" suppressHydrationWarning>
        <Providers>
          <Navbar />
          <main>{children}</main>
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              duration: 3000,
              style: {
                marginTop: "4rem",
                borderRadius: "999px",
                background: "#111214",
                color: "#f5f5f5",
                boxShadow: "0 10px 30px rgba(0,0,0,0.25)",
              },
            }}
          />
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
